### ISSUE TITLE
Not fetching videos form gallary

### ISSUE THREAD

**Issue by kashsbd** [Around25/react-native-gallery-media-picker#3] opened 2018-06-26 03:50 UTC
Hello there,Thanks for making this library.But it does not fetch videos from gallary.
Thanks.

**Comment by andreirat** [comment] 2018-06-27 05:42
@B4UGUYS , looks like there is a problem with displaying the video thumbnail. We'll fix this as soon as possible. Thanks !

**Comment by kashsbd** [comment] 2018-06-27 05:45
Thanks for your response.I am waiting for it.
Thanks again!

**Comment by AlexandruVoica** [comment] 2018-10-05 12:40
@B4UGUYS if you were asking for Android, it has been solved with the recent commit. :)

**Comment by kashsbd** [comment] 2018-10-06 03:28
Great work. Thanks !

**Comment by rafaismyname** [comment] 2019-01-29 12:40
Hey @AlexandruVoica, i can confirm that is properly working, so you might wanna close this issue.

BUT... it's taking up to 30 seconds to load my video gallery (groupTypes='All' assetType='Videos'), you might know why?

Best!

**Comment by rafaismyname** [comment] 2019-01-29 15:07
> Hey @AlexandruVoica, i can confirm that is properly working, so you might wanna close this issue.
> 
> BUT... it's taking up to 30 seconds to load my video gallery (groupTypes='All' assetType='Videos'), you might know why?
> 
> Best!

To everyone whom is having the same long loading time issue, just provide the property `firstLimit` and everything should be fine :)

Debugging i found out that this non-documented property `firstLimit` sets itself to 1000 by default, resulting in waiting up to 1000 files/thumbs to get loaded first.

Ex.:
```
<GalleryMediaPicker
            groupTypes="All"
            assetType="Videos"
            batchSize={1}
            firstLimit={30}
            emptyGalleryText={'There are no photos or video'}
            maximumSelectedFiles={1}
            selectSingleItem={true}
            selected={[]}
            itemsPerRow={3}
            imageMargin={3}
            callback={(files) => this.selectFile(files)} />
```

**Closed as completed** 2020-01-18 15:26 UTC
